name: Build Dawn
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest-large
    env:
      WORKING_DIRECTORY: ./packages/webgpu
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          link-to-sdk: true

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install Package
        run: yarn install --frozen-lockfile

      - name: Build Dawn
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: yarn build-dawn

      - name: Upload artifacts - Dawn Library Files
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: dawn-libs
          path: |
            packages/webgpu/libs
            packages/webgpu/cpp/dawn
            packages/webgpu/cpp/webgpu
